/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Ponto;
import Model.Quadrante;

/**
 *
 * @author sunse
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEixoX = new javax.swing.JTextField();
        tfEixoY = new javax.swing.JTextField();
        btAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chbkIncideX = new javax.swing.JCheckBox();
        chbkIncideY = new javax.swing.JCheckBox();
        chbkIPrimeiroQuad = new javax.swing.JCheckBox();
        chbkISegundoQuad = new javax.swing.JCheckBox();
        chbkITerceiroQuad = new javax.swing.JCheckBox();
        chbkIQuartoQuad = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X: ");

        jLabel2.setText("Eixo Y:");

        tfEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEixoXActionPerformed(evt);
            }
        });

        btAvaliar.setText("Avaliar");
        btAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição");

        chbkIncideX.setText("Incide sobre o Eixo X");
        chbkIncideX.setEnabled(false);
        chbkIncideX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbkIncideXActionPerformed(evt);
            }
        });

        chbkIncideY.setText("Incide sobre o Eixo Y");
        chbkIncideY.setEnabled(false);
        chbkIncideY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbkIncideYActionPerformed(evt);
            }
        });

        chbkIPrimeiroQuad.setText("No 1° Quadrante ");
        chbkIPrimeiroQuad.setEnabled(false);
        chbkIPrimeiroQuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbkIPrimeiroQuadActionPerformed(evt);
            }
        });

        chbkISegundoQuad.setText("No 2° Quadrante ");
        chbkISegundoQuad.setEnabled(false);
        chbkISegundoQuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbkISegundoQuadActionPerformed(evt);
            }
        });

        chbkITerceiroQuad.setText("No 3° Quadrante ");
        chbkITerceiroQuad.setEnabled(false);

        chbkIQuartoQuad.setText("No 4° Quadrante ");
        chbkIQuartoQuad.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btAvaliar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chbkIncideX, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbkIncideY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbkIPrimeiroQuad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbkISegundoQuad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbkITerceiroQuad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbkIQuartoQuad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btAvaliar)))
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(chbkIncideX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbkIncideY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbkIPrimeiroQuad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbkISegundoQuad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbkITerceiroQuad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbkIQuartoQuad)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEixoXActionPerformed

    private void chbkIPrimeiroQuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbkIPrimeiroQuadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbkIPrimeiroQuadActionPerformed

    private void chbkISegundoQuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbkISegundoQuadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbkISegundoQuadActionPerformed

    private void btAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliarActionPerformed

        int x = Integer.parseInt(tfEixoX.getText());
        int y = Integer.parseInt(tfEixoY.getText());

        Ponto meuponto = new Ponto();
        meuponto.setX(x);
        meuponto.setY(y);
        
        chbkIncideX.setSelected(meuponto.estaIncidindoSobreX());
        chbkIncideY.setSelected(meuponto.estaIncidindoSobreY());
        
        chbkIPrimeiroQuad.setSelected(meuponto.identificarQuadrante() == Quadrante.PRIMEIRO);
        chbkISegundoQuad.setSelected(meuponto.identificarQuadrante() == Quadrante.SEGUNDO);
        chbkITerceiroQuad.setSelected(meuponto.identificarQuadrante() == Quadrante.TERCEIRO);
        chbkIQuartoQuad.setSelected(meuponto.identificarQuadrante() == Quadrante.QUARTO);

    }//GEN-LAST:event_btAvaliarActionPerformed

    private void chbkIncideXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbkIncideXActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_chbkIncideXActionPerformed

    private void chbkIncideYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbkIncideYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbkIncideYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAvaliar;
    private javax.swing.JCheckBox chbkIPrimeiroQuad;
    private javax.swing.JCheckBox chbkIQuartoQuad;
    private javax.swing.JCheckBox chbkISegundoQuad;
    private javax.swing.JCheckBox chbkITerceiroQuad;
    private javax.swing.JCheckBox chbkIncideX;
    private javax.swing.JCheckBox chbkIncideY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfEixoX;
    private javax.swing.JTextField tfEixoY;
    // End of variables declaration//GEN-END:variables
}
